### ISSUE TITLE
Publish `larshp.vscode-source-map` to Open VSX

### ISSUE THREAD

**Issue by goyalyashpal** [larshp/vscode-source-map#3]
Hi!
Congratulations of getting ur extension [published]. I just thought to ask that do u have any plans to publish ur extension on open-vsx??
See this for more details: [larshp.vscode-source-map]
Thanks!

[published]: https://code.visualstudio.com/updates/v1_62#_web-extensions
[larshp.vscode-source-map]: https://open-vsx.org/vscode/item?itemName=larshp.vscode-source-map

**Comment by larshp** [comment]
not really, I dont think it has enough users for the trouble

**Comment by goyalyashpal** [comment]
ohkay (:
